### ISSUE TITLE
Mod dosn't work with GTNH 2.7.4 using Prism Launcher

### ISSUE THREAD

**Issue by pyottamus** [D-Cysteine/nesql-exporter#18]
As stated in the title, the mod fails to export anything in GTNH 2.7.4. The dev version doesn't even allow loading a world.

**Comment by WheelerShigley** [comment]
This may be different, but I'm having this problem in GTNH 2.8.4 (Client): 

```md
[10:30:49] [Thread-33/INFO]: [CHAT] §bExporting data to:
[10:30:49] [Thread-33/INFO]: [CHAT] C:\REDACTED\profiles\GregTech_ New Horizons (2.8.4 Client)\nesql\nesql-repository
[10:30:49] [Thread-33/INFO]: [java.lang.Throwable$WrappedPrintStream:println:790]: java.lang.NoClassDefFoundError: org/hibernate/jpa/HibernatePersistenceProvider
[10:30:49] [Thread-33/INFO]: [java.lang.Throwable$WrappedPrintStream:println:790]: 	at Launch//com.github.dcysteine.nesql.exporter.main.Exporter.export(Exporter.java:149)
[10:30:49] [Thread-33/INFO]: [java.lang.Throwable$WrappedPrintStream:println:790]: 	at Launch//com.github.dcysteine.nesql.exporter.main.Exporter.exportReportException(Exporter.java:80)
[10:30:49] [Thread-33/INFO]: [java.lang.Throwable$WrappedPrintStream:println:790]: 	at java.base/java.lang.Thread.run(Thread.java:1474)
[10:30:49] [Thread-33/INFO]: [java.lang.Throwable$WrappedPrintStream:println:790]: Caused by: java.lang.ClassNotFoundException: Class bytes are null for org.hibernate.jpa.HibernatePersistenceProvider (org.hibernate.jpa.HibernatePersistenceProvider, org.hibernate.jpa.HibernatePersistenceProvider)
[10:30:49] [Thread-33/INFO]: [java.lang.Throwable$WrappedPrintStream:println:790]: 	at System//net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:328)
[10:30:49] [Thread-33/INFO]: [java.lang.Throwable$WrappedPrintStream:println:790]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:557)
[10:30:49] [Thread-33/INFO]: [java.lang.Throwable$WrappedPrintStream:println:790]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
[10:30:49] [Thread-33/INFO]: [java.lang.Throwable$WrappedPrintStream:println:790]: 	... 3 more
```

**Comment by MasonGuinn** [comment]
Yup, can verify it does **NOT** work. Disappointing.

**Comment by fowdre** [comment]
> Yup, can verify it does **NOT** work. Disappointing. 

Hi, between the pack versions you will most likely have to update the dependencies manually so that it matches the version you are targeting.
